### ISSUE TITLE
New Tab in FireFox (Windows)

### ISSUE THREAD

**Issue by HoloSound** [HoloSound/AIC14W_G06_T02#10]
Example:

RAID1 / History - Delete a file:

Basis:

![newtab_1](https://cloud.githubusercontent.com/assets/5873171/5888145/7822008c-a3f4-11e4-8ccf-09d9d9f0eb00.png)

Delete Button -->

![newtab_2](https://cloud.githubusercontent.com/assets/5873171/5888148/85d744bc-a3f4-11e4-8f4e-2e52649eb5cf.png)

--> You see right beneath the open tab a "New Tab".

Confirming alert box:

![newtab_3](https://cloud.githubusercontent.com/assets/5873171/5888150/a1b5c03c-a3f4-11e4-989f-c4d76b0417f5.png)

"New Tab" stays!

![newtab_4](https://cloud.githubusercontent.com/assets/5873171/5888152/adfe9d8c-a3f4-11e4-9ee9-e3229e075444.png)

and has no useful content!

**Comment by HoloSound** [comment]
Use CHROME  (was the answer)!

**Comment by sherif181** [comment]
fixed

**Comment by sherif181** [comment]
Yes  also  i fixed it target='_blank' was the problem
