### ISSUE TITLE
UserInterface - RAID1 Delete File

### ISSUE THREAD

**Issue by HoloSound** [HoloSound/AIC14W_G06_T02#7]
RAID1 - deleting a file,
opens a "New Tab" in Firefox.
Shows the Delete successful message in MAIN Window. (Where the Delete button was pressed.)
But "New Tab" remains open without any information.

**Comment by sherif181** [comment]
works here   was probably fixed  by fixing the javascript imports

**Comment by HoloSound** [comment]
Hi

Than you for closing ... #7 !!!

Some other topic regarding gradle:

UBUNTU - in VM !

osboxes@osboxes:~/aic_ws/AIC14W_G06_T02-master$ ./gradlew cargoRunLocal 
--info

ERROR: JAVA_HOME is set to an invalid directory: /usr/bin/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

osboxes@osboxes:~/aic_ws/AIC14W_G06_T02-master$

osboxes@osboxes:~/aic_ws/AIC14W_G06_T02-master$ echo $JAVA_HOME
/usr/bin/java
osboxes@osboxes:~/aic_ws/AIC14W_G06_T02-master$

Installed Java via:

sudo apt-get install openjdk-8-jre-headless

wrong JAVA ?

br
Rainer

**Comment by sherif181** [comment]
Install a jdk  not  jre
If it does now work  install gradle
